pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            tools {
                jdk 'JDK11.0.9'
            }
            steps {
                sh 'mvn -v'
                sh 'mvn -X -B -DskipTests clean package'
            }
        }
        stage('Test') {
            tools {
                jdk 'JDK11.0.9'
            }
            steps {
                sh 'mvn -X test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
